apiVersion: v1

kind: Service

metadata:
  name: phpservice
  labels:
   servicelbl: phpservice
spec:
 type: NodePort
 ports:
  - nodePort: 32000
    port: 9000
    targetPort: 80

 selector:
  app: nginx
